site_name: 桐柏山
site_url: https://tongbaishan.netlify.app
copyright: 版权所有 &copy; 2024 桐柏一家人

nav:
  - 照片墙:
      - 尘封的记忆: photo-intro/olds.md
      - 方庄 (2011~ ): photo-intro/fangzhuang.md
      - 后沙峪 (2014~ ): photo-intro/houshayu.md
  - 放映厅:
      - 在北京: video-intro/beijing.md
  # - 档案馆:
  - 日记本:
      - blog/index.md
  - 桐柏美景: index.md

theme:
  name: material

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      # scheme: slate
      primary: yellow
      accent: orange
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: yellow
      accent: orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: yellow
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  language: zh

  logo: assets/logos/pine-cone.png
  favicon: assets/logos/pine-cone.png

  features:
    # - navigation.sections
    - navigation.tabs
    - navigation.instant # without fully reloading the page, fast loading function
    - navigation.tracking
    - navigation.path
    # - navigation.indexes ##enable it if you have an introduction to top level
    - navigation.top
    - header.autohide
    - navigation.footer
    - search.highlight
    - search.share
    - search.suggest
    - content.code.annotate
    - content.code.copy

extra:
  social:
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/
    - icon: fontawesome/solid/paper-plane
      link: longtsui@gmail.com
  generator: false
  # disqus: tongbaishan2
  # Disqus has been removed from mkdocs-material!!!
  # check out this thread: https://github.com/squidfunk/mkdocs-material/pull/3329

plugins:
  - search
  - tags
  - blog:
      draft_on_serve: false

markdown_extensions:
  # - meta
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - tables
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true

extra_css:
  - assets/css/styled-table.css
  # - https://unpkg.com/leaflet@1.9.4/dist/leaflet.css
  - assets/css/coverpic.css
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css
  - assets/css/icon.css
  - assets/css/youtube.css

extra_javascript:
  - assets/js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  # - https://unpkg.com/leaflet@1.9.4/dist/leaflet.js
